---
openapi: 3.0.3
info:
  version: 0.0.1
  title: Andook REST API
  description: Andook's REST API.
  license:
    name: MIT
    url: https://spdx.org/licenses/MIT
  # termsOfService: https://docs.github.com/articles/github-terms-of-service
  # contact:
  #   name: Support
  #   url: https://support.github.com/contact?tags=dotcom-rest-api
tags:
- name: transactions
  description: Endpoints to manage financial transactions using the REST API.
- name: meta
  description: Endpoints that give information about the API.
servers:
- url: https://api.andook.com
externalDocs:
  description: Andook REST API
  url: https://engineering.andook.com/rest/
paths:
  "/":
    get:
      summary: Andook API Root
      description: Get Hypermedia links to resources accessible in Andook's REST API
      tags:
      - meta
      operationId: meta/root
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/root"
              examples:
                default:
                  "$ref": "#/components/examples/root"
      # externalDocs:
      #   description: API method documentation
      #   url: https://docs.github.com/rest/overview/resources-in-the-rest-api#root-endpoint

components:
  schemas:
    root:
      type: object
      properties:
        version:
          type: string
          format: uri-template
      required:
      - version
  examples:
    root:
      value:
        "version": "0.1.0"
